### PR TITLE
v2-dev Refactoring Proposal 

### PR DESCRIPTION
**Pull request by kwhat**
Refactoring version 1.0 to be more Object Oriented in order to expand into other SQL domains.
Created a top level interface for all statement types and move a few components around.
Removed many convenience methods primarily to simplify the transition.
No effort has been made to add support beyond MySql at this point.

### CODE REVIEW

**Comment by kwhat** [comment]
Sorry I cant cleanup the commit anymore than that with history.  Let me know if you have questions on usage.

**Comment by zuozhehao** [comment]
$map1 = new \Slim\PDO\Clause\Conditional('roleid', '>', 1);
$map2 = new \Slim\PDO\Clause\Conditional('roleid', '<', 7);
$map   = new \Slim\PDO\Clause\Grouping('AND', [$map1 , $map2]);

`$map->getValues(); `// return emtpy;

$ret = $sta->where($map)->execute()->fetchAll();

Invalid parameter number in \PDO\AbstractStatement.php on line 122`

@kwhat

**Comment by kwhat** [comment]
@zuozhehao made some changes to address that and a few other issues.  In other news this branch is really hosed.

**Comment by kwhat** [comment]
@FaaPz are you still working on this?

**Comment by FaaPz** [comment]
@kwhat Wow, amazing work! I hadn't had the chance to look and test your changes thoroughly, but I will! 😄 

What do you suggest for this PR? We could merge it with `v2-dev` branch and continue to work on it with smaller changes, or would you like expand this PR a bit more?

**Comment by kwhat** [comment]
@FaaPz I am still testing it, so lets hold off until I feel like most of the bugs are worked out.  I got a little worried that your domain was down and you hadn't commented yet, but I am glad you are still working on the project.  When you have a moment take a look and let me know if you have any suggestions.

**Comment by kwhat** [comment]
@FaaPz I am feeling pretty good about the code that is there.  There are probably still some issues but we can merge this as soon as you're ready.  Feel free to assign bug reports to me and I will create new PR's.

**Comment by kwhat** [comment]
Hi @FaaPz,

Have you had any time to look at this PR and determine if this is a direction you want this project to go?  If not, its not a problem.  I am just trying to decide if I should hard fork or continue development here.

Thanks for an awesome lib.

Best,
Alex

**Comment by FaaPz** [comment]
@kwhat I truly appreciate the time and effort you have put into making this PR and I apologize for the late response.

Your PR is amazing and **yes**, this is definitely the more mature direction I would like to see this project going to. Let's merge and use your PR as new base for V2 and improve it from hereon! 🚀 

Slim-PDO is quite old (3+ years: 99e5032a8af32dfa60cd116139959f01e2f5cd4e) and with 62k installs on Packagist, I suspect now is the time to be more than simply the _"PDO database library for Slim Framework"_.

Requiring PHP 7.1 or higher (and using its great features), adding test coverage, improving documentation, maybe renaming (#20) are all things we could tackle once this PR is merged.

If you could fix the failed StyleCI analysis with a patch and then we're good to go! 😄

**Comment by kwhat** [comment]
@FaaPz Sound good!  As far as 7.1, you may want to reconsider moving up to 7 until 5.6 is EOL, I think it is happening soon.  The reason I bring this up, is there are still a lot of LTS distros that do not even officially support 5.6 (couch couch redhat).  What I have in this PR can reasonably support 5.6 - 7.2 and we can always roll up to the latest greatest when this 7.x stuff settles down a little more.  I have a few more ideas about spitting out into Database modules, I would like to be able to add postgres and mssql support, maybe stored procedures and maybe someway to split read writes.  Ill fix up the tests and we can go from there!  Thanks again for checkin it out and no worries on the wait.  I have been slammed with work myself.  As far as a title, how about _"Light Weight PDO Query Builder"_ :)

**Comment by FaaPz** [comment]
@kwhat Awesome! I see your point concerning the EOL, and I agree (but I'll miss [7.1 new features](http://php.net/manual/en/migration71.new-features.php) 😅).

I share your perception about adding "connectors" for various RDMSes and read/write connections would definitely be a nice addition to this project.

By the way, this branch has conflicts that must be resolved. I could do it myself locally, but then your hard work immortalized in the Git history ceases to exist. If you got the time, maybe merge `v2-dev` into yours to resolve the conflicts?

**Comment by kwhat** [comment]
@FaaPz All is good :+1:

**Pull request merged**
